name: Setup Node Environment

description: Install Node.js and project dependencies

runs:
  using: composite

  steps:

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - shell: bash
      run: npm ci