#version: "3.9"

services:
  api:
    build:
      context: .
      target: development

    container_name: feature-flag-api

    env_file:
      - .env.docker

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    command: npm run dev

    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: feature-flag-postgres

    environment:
      POSTGRES_DB: featureflags
      POSTGRES_USER: featureflags
      POSTGRES_PASSWORD: featureflags

    ports:
      - "6432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U featureflags"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: feature-flag-redis

    ports:
      - "6380:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis-data:/data

    restart: unless-stopped

  adminer:
    image: adminer
    container_name: feature-flag-adminer

    ports:
      - "8085:8080"

    depends_on:
      - postgres

    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  node_modules: