#version: "3.9"

services:
  api:
    build:
      context: .
      target: production

    container_name: feature-flag-api

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: feature-flag-postgres

    environment:
      POSTGRES_DB: featureflags
      POSTGRES_USER: featureflags
      POSTGRES_PASSWORD: featureflags

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U featureflags"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: feature-flag-redis

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis-data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  node_modules: