services:
  api:
    image: asia-southeast1-docker.pkg.dev/feature-flag-staging/feature-flag/feature-flag-service:${TAG:-latest}

    env_file:
      - .env.production

    restart: always

    read_only: true