name: Publish Staging Image

on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  docker:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'develop'

    name: Build & Publish Staging Image
    runs-on: ubuntu-latest

    concurrency:
      group: docker-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: true

    timeout-minutes: 20

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Publish Docker image
        uses: ./.github/actions/docker
        with:
          push: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/feature-flag-service:staging
            ghcr.io/${{ github.repository_owner }}/feature-flag-service:sha-${{ github.event.workflow_run.head_sha }}